name: Sync Blog Post

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          sshpass -p "$SSH_PASS" scp -r -P "$SSH_PORT" -o StrictHostKeyChecking=no source/_posts/* "${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}"
          sshpass -p "$SSH_PASS" ssh -p "$SSH_PORT" -o StrictHostKeyChecking=no "${SSH_USER}@${SSH_HOST}" "cd ${REMOTE_DIR} && hexo generate"